source 'https://github.com/iossocket/ReactNativeLib.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
use_frameworks!

def react_pods 
  pod 'FBLazyVector'
  pod 'FBReactNativeSpec'
  pod 'RCTRequired'
  pod 'RCTTypeSafety'
  pod 'React'
  pod 'React-Core'
  pod 'React-CoreModules'
  pod 'React-Core/DevSupport'
  pod 'React-RCTActionSheet'
  pod 'React-RCTAnimation'
  pod 'React-RCTBlob'
  pod 'React-RCTImage'
  pod 'React-RCTLinking'
  pod 'React-RCTNetwork'
  pod 'React-RCTSettings'
  pod 'React-RCTText'
  pod 'React-RCTVibration'
  pod 'React-Core/RCTWebSocket'

  pod 'React-cxxreact'
  pod 'React-jsi'
  pod 'React-jsiexecutor'
  pod 'React-jsinspector'
  pod 'ReactCommon/jscallinvoker'
  pod 'ReactCommon/turbomodule/core'
  pod 'Yoga'

  pod 'DoubleConversion'
  pod 'glog'
  pod 'Folly'
end

target 'RNModule' do
  react_pods

  target 'RNModuleTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

def lib_dir
  project './RNLib/RNLib.xcodeproj'
  workspace 'RNModule'
end

target "RNLib" do
  lib_dir
  inherit! :search_paths
  react_pods
end

target 'RNLibTests' do
  lib_dir
  inherit! :search_paths
  react_pods
end

post_install do |installer|
  installer.pods_project.build_configuration_list.build_configurations.each do |configuration|
    configuration.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
  end
end